	<main class="main">
		<div class="container">
			<h2>Notre volonté : vous faire découvrir des produits typiques du Mexique.</h2>

			<p class="desc_main">En créant notre boutique en ligne, nous avions un souhait qui nous anime toujours. Nous voulions vous offrir des accessoirs qui sont utilisés depuis toujours par les habitants de ce pays d’Amérique Latine. Grâce à notre site, nous pouvons partager avec vous notre passion pour la culture mexicaine. C’est pourquoi vous retrouvez une sélection très complète de produits sur notre site. Régulièrement, nous ajoutons des nouveautés pour vous fournir toujours plus de choix à des petits prix.</p>


			<h2>Un catalogue varié de références à commander sur notre boutique.</h2>

			<p class="desc_main">Afin de vous présenter une vision globale des traditions du Mexique, nous mettons à votre disposition une gamme très complète d’articles sur notre magasin en ligne. Vous retrouvez donc des chapeaux, ponchos, ... Lors de vos achats, si vous avez des questions, notre équipe est à votre écoute alors n’hésitez pas à nous contacter pour en savoir plus !</p> 
		</div>
	</main>






