<form class="form" method="POST">
	<input type="hidden" name="action" value="add">
	<input type="hidden" name="id_product" value="<?=htmlentities($product->getId())?>">
	<label class="prod_quantity" for="quantity">Quantité</label>
	<input type="number" id="quantity" max="<?=htmlentities($product->getStock())?>" min="0" class="stock" name="quantity">
	<br>
	<button type="submit" class="button btn btn-info">Ajouter au panier</button>
</form>