<hr>
<article class="article-center">
	<h3><?=htmlentities($product->getTitle())?></h3>
	<p><?=htmlentities($product->getProduct())?></p>
	<div class="art_date">Posté le : <?=htmlentities($product->getDate())?></div>
	<div class="art_author">De : <?=htmlentities($product->getProduct()->getLogin())?></div>
</article>
<?php
require('apps/comments.php');
require('apps/create_comment.php');
require('apps/del_comment.php');
?>

