<hr>
<article class="article-center">
	<h3><?=htmlentities($article->getTitle())?></h3>
	<p><?=htmlentities($article->getArticle())?></p>
	<div class="art_date">Posté le : <?=htmlentities($article->getDate())?></div>
	<div class="art_author">De : <?=htmlentities($article->getAuthor()->getLogin())?></div>
</article>
<?php
require('apps/comments.php');
require('apps/create_comment.php');
require('apps/del_comment.php');
?>

