<div class="container">
	<article class="comment-center comment">
		<h3 class="comment_user"><?=htmlentities($comment->getAuthor()->getLogin())?> :</h3>
		<div class="comment_date"><?=htmlentities($comment->getDate())?></div>
			<?php
				$i = 1;
				while ($i <= 5)
				{
					if ($i <= intval($comment->getNote()))
						echo '<span class="starOn">☆</span>';
					else
						echo '<span class="starOff">☆</span>';
	    			$i++;  /* La valeur affichée est $i avant l'incrémentation (post-incrémentation)  */
				}
			?>
		<div class="comment_content"><?=htmlentities($comment->getContent())?></div>
		<br>
	</article>
</div>

