<div>CONTAINER</div>
<?php
require("apps/errors.php");
require('apps/'.$page.'.php');
// require('apps/register.php');
// require('apps/login.php');
// require('apps/create_article.php');
// require('apps/article.php');
// require('apps/articles.php');
// require('apps/edit_article.php');
?>


	<main class="main">
		<div class="container">
			<div class="row">
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-1.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-2.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-3.jpg" alt="">
								<figcaption class="post-price"><span>$2500</span></figcaption>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-1.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-2.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-3.jpg" alt="">
								<figcaption class="post-price"><span>$2500</span></figcaption>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-1.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-2.jpg" alt="">
								<div class="post-price"><span>$2500</span></div>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
				<div class="col-lg-4 col-sm-6">
					<article class="post">
						<figure class="post-thumbnail">
							<a href="#">
								<img src="./images/property-3.jpg" alt="">
								<figcaption class="post-price"><span>$2500</span></figcaption>
							</a>
						</figure>
						<div class="post-content">
							<h2 class="post-content-title">Fuisque dictum tortor at purus libero</h2>
							<div class="post-content-excerpt">2 kitchens, 2 beds, 2 bath... <span>(288ftsq)</span></div>
						</div>
					</article>
				</div>
			</div>

			<div class="text-center">
				<a href="" class="button-radius">View more listings</a>
			</div>
		</div>
	</main>