<div class="container">
	<div class="page">
		<form method="post">
			<div class="form-saut">
				<label for="message">Votre avis : </label>
				<br>
				<textarea id="message" placeholder="Votre commentaire..." name="comment"></textarea>
				<br>
				<button type="button" class="btn btn-outline-primary">Envoyer</button>
				<input type="hidden" name="id_product" value="<?=$product->getId()?>">
			</div>
		</form>
	</div>
</div>
