<div class="container">
	<div class="page">
		<form method="post">
			<div class="form-saut">
				<label for="message">Votre avis : </label>
				<br>
				<div class="rating"><!--
				   --><a href="#5" title="Donner 5 étoiles" data-note="5">☆</a><!--
				   --><a href="#4" title="Donner 4 étoiles" data-note="4">☆</a><!--
				   --><a href="#3" title="Donner 3 étoiles" data-note="3">☆</a><!--
				   --><a href="#2" title="Donner 2 étoiles" data-note="2">☆</a><!--
				   --><a href="#1" title="Donner 1 étoile" data-note="1">☆</a>
				</div>

				<!-- Clickez sur l'étoile de votre choix pour valider le vote:<br /><br />
<img src="star1.gif" id='_1' onclick="valider()" onmouseover="rate(1)" /><img src="star1.gif" id='_2' onclick="valider()"  onmouseover="rate(2)" /><img src="star1.gif" id='_3' onclick="valider()"  onmouseover="rate(3)" /><img src="star1.gif" id='_4' onclick="valider()"  onmouseover="rate(4)"  /><img src="star1.gif" id='_5' onclick="valider()"  onmouseover="rate(5)"  />
<br /><br/>
<div id="vote">Votre vote : 0 étoile(s) </div><br /><br/>
<input type="button" onclick="zero();" value="reset"/> -->


				<br>
				<input type="hidden" name="note" value="" id="note">
				<textarea id="message" placeholder="Votre commentaire..." cols="80" rows="10" name="comment"></textarea>
				<br>
				<button type="submit" class="btn btn-outline-primary">Envoyer</button>
				<input type="hidden" name="id_product" value="<?=$product->getId()?>">
			</div>
		</form>
	</div>
</div>
<script>
$('.rating>a').click(function()
{
	var note = $(this).data('note');
	$('#note').val(note);
});
</script>


<!-- var done=false
var pic = new Array();
pic[0]=new Image();
pic[0].src="star1.gif";
pic[1]=new Image();
pic[1].src="star2.gif";
var bareme = new Array("peu ","passablement ","moyennement","presque","") 
 
 function rate(level){
 if (done){return false;}
  for(i=1;i<6;i++){ document.getElementById('_'+i).src=(level<i)?pic[0].src:pic[1].src;
  document.getElementById('vote').innerHTML=""+bareme[level-1]+" satisfaisant" 
  }
  }
 
 function zero(){
     for(i=1;i<6;i++){ document.getElementById('_'+i).src=pic[0].src;
     done=false;
     document.getElementById('vote').innerHTML="Votre vote : 0 étoile(s)" 
 
     }
     }
 function valider(){
 done=true;
 document.getElementById('vote').innerHTML+='   VALID&Eacute;'
 } -->