<hr>
<div class="new_article">
<h2>Nouvel article</h2>
	<form method="post">
		
	    <div>
	        <label for="title">Titre :</label>
	        <input type="text" id="title" name="title" />
	    </div>
		<div class="form-saut">
			<label for="message">Votre message : </label>
			<textarea name="article" id="message" placeholder="Votre article..." ></textarea>
			<button>Envoyer</button>
		</div>
	</form>
</div>