<div class="container">
	<div class="page">
	<h2>Nouvelle catégorie</h2>
		<form method="post">
		
		    <div>
		        <label for="categorie">Catégorie</label>
		        <input type="text" id="cat_name" name="categorie" />
		    </div>

			<div class="form-desc">
				<label for="cat_desc">Description : </label>
				<textarea name="cat_desc" id="cat_desc" placeholder="Description de la categorie" ></textarea>
			</div>

			<div class="button"><button>Envoyer</button></div>

		</form>
	</div>
</div>