<div class="container">
	<div class="page">
		<form method="post" action="index.php?page=comments">
			<div class="form-saut">
				<label for="message">Votre avis : </label>
				<br>
				<div class="rating">
				   <a href="#5" title="Donner 5 étoiles" data-note="5">☆</a>
				   <a href="#4" title="Donner 4 étoiles" data-note="4">☆</a>
				   <a href="#3" title="Donner 3 étoiles" data-note="3">☆</a>
				   <a href="#2" title="Donner 2 étoiles" data-note="2">☆</a>
				   <a href="#1" title="Donner 1 étoile" data-note="1">☆</a>
				</div>
				<br>
				<input type="hidden" name="note" value="" id="note">
				<textarea id="message" placeholder="Votre commentaire..." cols="80" rows="10" name="comment"></textarea>
				<br>
				<button type="submit" class="btn btn-outline-primary">Envoyer</button>
				<input type="hidden" name="id_product" value="<?=$product->getId()?>">
			</div>
		</form>
	</div>
</div>
<script>
$('.rating>a').click(function()
{
	var note = $(this).data('note');
	$('#note').val(note);
});
</script>