<hr>
<div class="new_product">
<h2>Nouvel product</h2>
	<form method="post">
		
	    <div>
	        <label for="prod_name">Produit :</label>
	        <input type="text" id="prod_name" name="prod_name" />
	    </div>
		<div class="form-saut">
			<label for="prod_desc">Description : </label>
			<textarea name="desc" id="desc" placeholder="Description de l'article..." ></textarea>

 		<div>
	        <label for="price">Prix :</label>
	        <input type="text" id="prod_name" name="prod_name" />  €
	    </div>

		<div>
	        <label for="image">Lien de l'image :</label>
	        <input type="text" id="image" name="image" />  €
	    </div>

	    <div>
	        <label for="stock">Combien en stock :</label>
	        <input type="text" id="stock" name="stock" />
	    </div>

			<button>Envoyer</button>
		</div>
	</form>
</div>