<hr>
<div class="new_product">
<h2>Nouveau produit</h2>
	<form method="post">
		
	    <div>
	        <label for="prod_name">Produit :</label>
	        <input type="text" id="prod_name" name="prod_name" />
	    </div>
		<div class="form-saut">
			<label for="prod_desc">Description : </label>
			<textarea name="prod_desc" id="desc" placeholder="Description du produit..." ></textarea>

 		<div>
	        <label for="price">Prix :</label>
	        <input type="text" id="price" name="price" />  €
	    </div>

		<div>
	        <label for="image">Lien de l'image :</label>
	        <input type="text" id="image" name="image" /> 
	    </div>

		<div>
	        <label for="prod_cover">Miniature:</label>
	        <input type="text" id="prod_cover" name="prod_cover" /> 
	    </div>

	    <div>
	        <label for="stock">Combien en stock :</label>
	        <input type="text" id="stock" name="stock" />
	    </div>

	    <div>
			<label for="id_category">Categorie :</label>
                    <select id="id_category" name="id_category">
                        <option value="1">Chapeaux</option>
                        <option value="2">Ponchos</option>
                        <option value="3">Accesoires</option>
                    </select>
	    </div>

			<button>Envoyer</button>
		</div>
	</form>
</div>