<hr>
<div class="new_product">
<h2>Nouveau produit</h2>
	<form method="post">
		<div>
	        <label for="prod_name">Name :</label>
	        <input type="text" id="prod_name" />
	    </div>
		<div class="form-saut">
			<label for="message">Votre message : </label>
			<textarea name="message" id="message" placeholder="Dites moi ce que vous attendez de moi !" ></textarea>
			<button>Envoyer</button>
		</div>
	</form>
</div>