<hr>
<div class="new_article">
<h2>Nouvel article</h2>
	<form method="post">
		<div>
	        <label for="author">Auteur :</label>
	        <input type="text" id="author" />
	    </div>
		<div class="form-saut">
			<label for="message">Votre message : </label>
			<textarea name="message" id="message" placeholder="Dites moi ce que vous attendez de moi !" ></textarea>
			<button>Envoyer</button>
		</div>
	</form>
</div>