	<footer class="footer">
		<div class="container">
			<!-- <div class="row"> -->
				<div class="footer-align">
					<!-- <ul class="list-unstyled"> -->
						<a href="">About</a>
						<a href="">Support</a>
						<a href="">Terms</a>
						<a href="">Contact</a>
						<!-- <a href="">Policy</a> -->
					<!-- </ul> -->
				</div>
				<!-- <div class="col-md-3 col-sm-6">
					<ul class="list-unstyled">
						<li><a href="">Appartements</a></li>
						<li><a href="">Villas</a></li>
						<li><a href="">Houses</a></li>
						<li><a href="">Chapeaux</a></li>
						<li><a href="">Poncho</a></li>
					</ul>
				</div> -->
				<!-- <div class="col-md-3 col-sm-6">
					<ul class="list-unstyled">
						<li><a href="">Mexico</a></li>
						<li><a href="">Guadalajara</a></li>
						<li><a href="">Monterrey</a></li>
						<li><a href="">Tijuana</a></li>
						<li><a href="">Cancún</a></li>
					</ul>
				</div> -->
				<!-- <div class="col-md-3 col-sm-6"> -->
					<p>La Fiesta Loca is real estate minimal html5 web-site template, designed and coded by pixel-hint, tellus varius, dictum erat vel, maximus tellus. Sed vitae auctor ipsum.</p>

					<ul class="footer-social list-inline">
						<li><a href=""><i class="fa fa-facebook"></i></a></li>
						<li><a href=""><i class="fa fa-twitter"></i></a></li>
						<li><a href=""><i class="fa fa-git"></i></a></li>
						<li><a href=""><i class="fa fa-skype"></i></a></li>
					</ul>
				<!-- </div> -->
			<!-- </div> -->

			<div class="footer-copyright">
				<div class="text-center">Copyright &copy; 2017 Mexicano.com. All Rights Reserved</div>
			</div>
		</div>
	</footer>
	
	<script src="scripts/jquery.min.js"></script>
	<script src="scripts/bootstrap.min.js"></script>
	<script>
		$(window).scroll(function() {
			var srtop = $("body").scrollTop();
			$(".header-nav").css("background-color","rgba(28,54,85,"+(srtop/800+0.2)+")");
		});
	</script>