	<footer class="footer">
		<div class="container">
			<div class="footer-align">

				<a href="">About</a>
				<a href="">Support</a>
				<a href="">Terms</a>
				<a href="">Contact</a>
			
				<p>La Fiesta Loca is real estate minimal html5 web-site template, designed and coded by team Mexicano, tellus varius, dictum erat vel, maximus tellus. Sed vitae auctor ipsum.</p>
			</div>

			<ul class="footer-social list-inline">
				<li><a href=""><i class="fa fa-facebook"></i></a></li>
				<li><a href=""><i class="fa fa-twitter"></i></a></li>
				<li><a href=""><i class="fa fa-git"></i></a></li>
				<li><a href=""><i class="fa fa-skype"></i></a></li>
			</ul>

			<div class="footer-copyright">
				<div class="text-center">Copyright &copy; 2017 Mexicano.com. All Rights Reserved</div>
			</div>
		</div>
	</footer>
	
	<script src="scripts/jquery.min.js"></script>
	<script src="scripts/bootstrap.min.js"></script>
	<script>
		$(window).scroll(function() {
			var srtop = $("body").scrollTop();
			$(".header-nav").css("background-color","rgba(28,54,85,"+(srtop/800+0.2)+")");
		});
	</script>