<header class="header">
		<nav class="header-nav">
			<div class="container">
				<div class="header-nav-logo">
					<a href=""><img src="images/fiesta-logo.png"></a>
				</div>
				<nav class="header-nav-menu">
					<ul class="list-inline">
						<li><a href="">Produits</a>
							<ul>
								<li><a href="#">Chapeaux</a></li>
								<li><a href="#">Poncho</a></li>
								<li><a href="#">Accessoire</a></li>
							</ul>
						</li>
						<li><a href="">Recherche</a></li>
						
						<li><a href="" class="header-nav-menu-login">Login</a></li>
					</ul>
				</nav>
			</div>
		</nav>

		<div class="header-title text-center text-capitalize">
			<h1>Find your dream home<span>Appartments - Houses - Mansions</span></h1>
		</div>
	</header>