<header class="header">
		<nav class="header-nav">
			<div class="container">
				<div class="header-nav-logo">
					<a href="index.php"><img src="public/images/fiesta-logo.png"></a>
				</div>
				<nav class="header-nav-menu">
					<ul class="list-inline sousmenu">
						<li><a href="index.php?page=products">Produits</a>
							<ul>
								<?php foreach ($list AS $categorie) : ?>
									<li><a href="index.php?page=products&id_category=<?=$categorie->getId()?>"><?=$categorie->getCatName()?></a></li>
								<?php endforeach; ?>
							</ul>
						</li>
						<li><a href="index.php?page=create_product">Créer un produit</a></li>
						<li><a href="index.php?page=create_categorie">Créer une catégorie</a></li>

						
						<li><a href="index.php?page=cart"><i class="fa fa-cart-arrow-down"></i>

						<li class="dropdown">
							<a href="index.php?page=profil" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=htmlentities($_SESSION['login'])?> <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="index.php?page=profil">Profil</a></li>

								<li><a href="index.php?page=logout">Logout</a></li>
							</ul>
						</li>
						
						</a></li>

					</ul>
				</nav>
			</div>
		</nav>

		<div class="header-title text-center text-capitalize">
			<h1>Hola Chica<span>Poncho - Chapeaux - Accessoires</span></h1>
		</div>
	</header>
	
	<div class="search">
		<div class="container">
			<form method="GET" >
				<input type='hidden' name="page" value="result">
				<input type="text" name="mot" class="search-field" placeholder="Rechercher...">
				<button type ="submit" class="search-button" name="recherche"><i class="fa fa-search"></i></button>
			</form>
		</div>
	</div>