<header class="header">
		<nav class="header-nav">
			<div class="container">
				<div class="header-nav-logo">
					<a href="index.php"><img src="public/images/fiesta-logo.png"></a>
				</div>
				<nav class="header-nav-menu">
					<ul class="list-inline sousmenu">
						<li><a href="index.php?page=products">Produits</a>
							<ul>
								<li><a href="index.php?page=products">Chapeaux</a></li>
								<li><a href="index.php?page=products">Poncho</a></li>
								<li><a href="index.php?page=products">Accessoire</a></li>
							</ul>
						</li>

						
						<li><a href="index.php?page=cart"><i class="fa fa-cart-arrow-down"></i>

						<li class="dropdown">
							<a href="index.php?page=profil" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=htmlentities($_SESSION['login'])?> <span class="caret"></span></a>
							<ul class="dropdown-menu">
								<li><a href="index.php?page=profil">Profil</a></li>

								<li><a href="index.php?page=logout">Logout</a></li>
							</ul>
						</li>
						
						
						</a></li>

					</ul>
				</nav>
			</div>
		</nav>

		<div class="header-title text-center text-capitalize">
			<h1>Hola Chica<span>Poncho - Chapeaux - Accessoires</span></h1>
		</div>
	</header>

	<div class="search">
		<div class="container">
			<form action="">
				<input type="text" name="s" class="search-field" placeholder="What are you looking for ?">
				<button class="search-button"><i class="fa fa-search"></i></button>
			</form>
		</div>
	</div>