<header><h1>HEADER en H1 !</h1>
	<nav class="navbar navbar-default">
	  <div class="container-fluid">
	    <div class="navbar-header">
	      <a class="navbar-brand" href="index.php">LOGO</a>
	    </div>
	    <ul class="nav navbar-nav">
	      <li><a href="?page=articles">Articles</a></li>

	    </ul>
	    <ul class="nav navbar-nav navbar-right">
				<li class="dropdown">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false"><?=htmlentities($_SESSION['login'])?> <span class="caret"></span></a>
					<ul class="dropdown-menu">
						<li><a href="index.php?page=logout">Logout</a></li>
					</ul>
				</li>
			</ul>
	  </div>
	</nav>
</header>