<div class="container">
    <div class="login">
        <h2>Login</h2>
        <form method="post">
            <input type="hidden" name="action" value="login">
            <div>
                <label for="login">Login :</label>
                <input type="text" id="login" name="login"/>
            </div>
            <div>
        	   <label for="psw">Mot de passe :</label>
        	   <input type="password" name="password" id="psw">
            </div>
       
            <div class="button"><button>Se connecter</button></div>
             </form>
        <a href="index.php?page=register">Si vous n'avez pas de compte, cliquez-ici</a>
    </div>
</div>