<hr>
<div class="login">
    <h2>Login</h2>
    <form method="post">
    <input type="hidden" name="action" value="login">
        <div>
            <label for="login">Login :</label>
            <input type="text" id="login" name="login"/>
        </div>
        <div>
        	<label for="psw">Mot de passe :</label>
        	<input type="password" name="password" id="psw">
        </div>
        <button>
      	 	Se connecter
      	 </button>
    </form>
</div>