<div class="container">
	<div class="row">
		<div class="col-lg-6 col-sm-6">
			<article class="post_prod">
				<h3 class="prod_category">Categorie <?=htmlentities($product->getCategory()->getCatName())?></h3>
				<div class="post"><img src="<?=htmlentities($product->getImage())?>"></div>
			</article>
		</div>

		<div class="col-lg-6 col-sm-6">
			<article class="post_prod">
				<div class="prod_name"><?=htmlentities($product->getProdName())?></div>
				<div class="prod_desc"><span>Description </span>: <?=htmlentities($product->getProdDesc())?></div>
				<div class="prod_price"><span>Prix :</span> <?=htmlentities($product->getPrice())?> €</div>
				<div class="prod_stock"><span>En stock :</span> <?=htmlentities($product->getStock())?></div>
				<?php
				if (!isset($_SESSION['id']))
				{
					echo '<a href="index.php?page=login">Connectez-vous</a>';
				}
				require('apps/add_product.php');
				?>
			</article>
		</div>
	</div>
</div>
<?php
require('apps/comments.php');
require('apps/create_comment.php');
require('apps/del_comment.php');
?>