<hr>
<article class="prod_name">
	<h3><?=htmlentities($product->getProdName())?></h3>
	<div class="prod_date">Posté le : <?=htmlentities($product->getDate())?></div>
	<div class="prod_category">De : <?=htmlentities($product->getProdDesc()->getIdCategory())?></div>
	<div class="prod_price"><?=htmlentities($product->getPrice()?> €</div>
	<div class="prod_image"><?=htmlentities($product->getImage())?></div>
	<div class="prod_stock">En stock <?=htmlentities($product->getStock())?></div>

</article>
<?php
require('apps/comments.php');
require('apps/create_comment.php');
require('apps/del_comment.php');
?>

