<div class="container">
	<div class="page">
    <h2><?=htmlentities($_SESSION['login'])?></h2>
    <form>
        <div>
        	<label for="psw">Modifier l'identifiant:</label>
        	<input type="text" name="identifiant" placeholder="Identifiant" value="<?=$user->getLogin()?>">
        </div>
        <div>
        	<label for="psw">Modifier le mot de passe:</label>
        	<input type="text" name="new mdp" placeholder="Mot de passe">
        </div>
        <div>
        	<label for="psw">Modifier l'adresse:</label>
        	<input type="modifadress" name="modifadress" placeholder="Adresse" value="<?=$user->getAdress()?>">
        </div>
        <div>
        	<label for="psw">Ajouter une nouvelle adresse:</label>
        	<input type="newad" name="newad" placeholder="New adresse">
        </div>
        <div class="button_2"><button>Valider</button></div>
    </form>
    
        <div class="lastcommand">
            <h3>Voici vos dernières commandes</h3>
            <ul>  
                <li><a href="index.php?page=cart">Commande en cours</a></li>
                <li><a href="index.php?page=cart">Suivis de la commande</a></li>
                <li><a href="index.php?page=cart">Historique</a></li>
            </ul>
        </div>

	</div>
</div>