<div class="container">
	<h1><?=htmlentities($_SESSION['login'])?> </h1>
	<div class="profil">
	<ul>
			
		<li><a href="">Modifier votre profil</a></li>
		<li><a href="">Modifier l'adresse</a></li>
		<li><a href="">Ajouter une nouvelle adresse</a></li>
		<li><a href="">Modifier le mot de passe</a></li>
		<li><a href="">Modifier l'identifiant</a></li>

		</ul>
	</div>

	<div class="lastcommand">

		<h2>Voici vos dernières commandes</h2>
		<ul>
			
		<li><a href="index.php?page=cart">Commande en cours</a></li>
		<li><a href="index.php?page=cart">Suivis de la commande</a></li>
		<li><a href="index.php?page=cart">Historique</a></li>

		</ul>

	</div>
</div>