<!DOCTYPE html>
<html lang="fr">
<head>
	<meta charset="UTF-8">
	<title>MVC Exemple 1</title>
	<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
	<link href="https://fonts.googleapis.com/css?family=Caveat" rel="stylesheet">
	<link type="text/css" rel="stylesheet" href="css/bootstrap.min.css">
	<link type="text/css" rel="stylesheet" href="css/bootstrap-theme.css">	
	<link type="text/css" rel="stylesheet" href="css/style.css">

</head>
<body>
	<div class="container">
		<?php require('apps/header.php'); ?>
		<?php require('apps/container.php'); ?>
		<?php require('apps/footer.php'); ?>
	</div>
	<script src="js/jquery.js"></script>
	<script src="js/bootstrap.min.js"></script>
</body>
</html>